In [1]:
import pandas as pd
import numpy as np

In [2]:
flights = pd.read_csv('data/flights.csv')

In [3]:
fp = flights.pivot_table(index='AIRLINE',columns='ORG_AIR',values='CANCELLED',aggfunc='sum',fill_value=0).round(2)

In [4]:
 fp.head()

ORG_AIR  ATL  DEN  DFW  IAH  LAS  LAX  MSP  ORD  PHX  SFO
AIRLINE
AA         3    4   86    3    3   11    3   35    4    2
AS         0    0    0    0    0    0    0    0    0    0
B6         0    0    0    0    0    0    0    0    0    1
DL        28    1    0    0    1    1    4    0    1    2
EV        18    6   27   36    0    0    6   53    0    0

In [5]:
fg = flights.groupby(['AIRLINE', 'ORG_AIR'])['CANCELLED'].sum()

In [6]:
 fg.head()

AIRLINE  ORG_AIR
AA       ATL         3
         DEN         4
         DFW        86
         IAH         3
         LAS         3
Name: CANCELLED, dtype: int64

In [7]:
fg_unstack = fg.unstack('ORG_AIR', fill_value=0)

In [8]:
 fp.equals(fg_unstack)

True

In [9]:
flights.pivot_table(index=['AIRLINE', 'MONTH'],columns=['ORG_AIR', 'CANCELLED'],values=['DEP_DELAY', 'DIST'],aggfunc=[np.sum, np.mean],fill_value=0)

                    sum                                              ...       \
              DEP_DELAY                                              ...
ORG_AIR             ATL      DEN      DFW      IAH        LAS        ...
CANCELLED             0  1     0  1     0  1     0    1     0  1     ...
AIRLINE MONTH                                                        ...
AA      1           -13  0   113  0  4276 -3   117    0  1036  0     ...
        2           -39  0    71  0  2662  0     8    0   -55  0     ...
        3            -2  0    69  0  5692  0   109    0   326  0     ...
        4             1  0   304  0  3518  0   104    0   790  0     ...
        5            52  0   352  0  5510  0    55    0    93  0     ...
        6            96  0    11  0  6557  0   543    0   883  0     ...
        7           575  0    80  0  4461  0  1015    0   330  0     ...
        8           132  0   588  0  3773  0   139    0   226  0     ...
        9           383  0   116  0  2411  0    45    0   -74  0     ...
        11          258  0   404  0  3496  0   130    0   299  0     ...
        12          396  0   121  0  2380  0   253    0   -15  0     ...
AS      1             0  0   -17  0    -6  0     0    0   105  0     ...
        2             1  0   -15  0    16  0     0    0   654  0     ...
        3            -2  0   -36  0    14  0     0    0   -53  0     ...
        4             7  0   -15  0    12  0     8    0   -62  0     ...
        5            68  0     4  0    90  0   -15    0   102  0     ...
        6             0  0    29  0     2  0   -13    0   -54  0     ...
        7             0  0    16  0   -31  0    -9    0   -55  0     ...
        8            41  0   -40  0    13  0     0    0  -101  0     ...
        9             0  0    -7  0   -25  0    -6    0   -26  0     ...
        11           -3  0   -24  0   -14  0     0    0   -86  0     ...
        12           87  0   -25  0    57  0   -13    0   -72  0     ...
B6      1             0  0     9  0    -1  0     0    0   236  0     ...
        2             0  0    71  0    63  0     0    0    91  0     ...
        3             0  0    62  0     0  0     0    0   136  0     ...
        4             0  0   -15  0    -7  0     0    0   -17  0     ...
        5             0  0    15  0    -8  0     0    0    13  0     ...
        6             0  0    67  0    21  0     0    0   194  0     ...
        7             0  0     0  0     0  0     0    0   225  0     ...
        8             0  0    38  0    63  0     0    0   226  0     ...
...                 ... ..   ... ..   ... ..   ...  ...   ... ..     ...
UA      11          186  0   983  0   -17  0  1940    0   466  0     ...
        12          350  0  2515  0   136  0  2885  227   852  0     ...
US      1           -38  0     3  0    47  0   -52    0   -75  0     ...
        2            -3  0    59  0    20  0    22    0   -56  0     ...
        3           -40  0    29  0   140  0   -58    0   -29  0     ...
        4           -26  0   -75  0   108  0    50    0   -17  0     ...
        5           128  0    87  0    35  0   -27    0   -51  0     ...
        6           125  0   -27  0   255  0   -19    0   -12  0     ...
VX      1             0  0     0  0     0  0     0    0    26  0     ...
        2             0  0     0  0     0  0     0    0   107  0     ...
        3             0  0     0  0     0  0     0    0     4  0     ...
        4             0  0     0  0     0  0     0    0    93  0     ...
        5             0  0     0  0     0  0     0    0    80  0     ...
        6             0  0     0  0     0  0     0    0    47  0     ...
        7             0  0     0  0     0  0     0    0   239  0     ...
        8             0  0     0  0     0  0     0    0    22  0     ...
        9             0  0     0  0     0  0     0    0   -14  0     ...
        11            0  0     0  0     0  0     0    0    38  0     ...
        12            0  0     0  0     0  0     0    0    24  0     ...
WN      1           894  0  1827  0     0  0     0    0  1512  0     ...
        2           714  0  1364  0     0  0     0    0  1058  0     ...
        3          1170  0  1909  0     0  0     0    0  2280  0     ...
        4          1240  0  1882  0     0  0     0    0  1993  0     ...
        5          1964  0  2094 -2     0  0     0    0  2271  0     ...
        6          2533  0  2427  0     0  0     0    0  3123  0     ...
        7          2604  0  1919  0     0  0     0    0  4600  0     ...
        8          1718  0  1180  0     0  0     0    0  3151  0     ...
        9          1033  0   705  0     0  0     0    0  1400  0     ...
        11          700  0  1372  0     0  0     0    0  1309  0     ...
        12         1679  0  1898  0     0  0     0    0  2327  0     ...

                      mean                                                \
                      DIST
ORG_AIR                LAX                       MSP                 ORD
CANCELLED                0            1            0      1            0
AIRLINE MONTH
AA      1      1678.037037  2475.000000   809.000000    0.0  1068.876033
        2      1745.892308  1818.000000  1008.000000    0.0  1193.782178
        3      1781.567568  1744.000000   964.733333    0.0  1058.933333
        4      1850.923913     0.000000   648.714286    0.0  1094.633094
        5      1820.478261     0.000000   787.250000    0.0   998.774775
        6      1761.711111     0.000000   884.750000    0.0  1181.646259
        7      1814.085106     0.000000   993.578947  980.0  1073.920245
        8      1650.580357  2150.000000   874.529412    0.0  1034.883871
        9      1777.532468  1235.000000   830.300000    0.0   998.514286
        11     1559.305263  1744.000000   846.136364  930.0  1002.088889
        12     1829.284314  2115.000000   883.666667  334.0  1080.720930
AS      1       984.176471     0.000000  1399.000000    0.0  2096.000000
        2      1022.421053     0.000000     0.000000    0.0  1721.000000
        3       905.840000     0.000000  1399.000000    0.0  1725.500000
        4      1115.347826     0.000000     0.000000    0.0  2006.750000
        5      1023.500000     0.000000  1399.000000    0.0  1863.875000
        6      1088.275862     0.000000  1399.000000    0.0  1724.600000
        7       975.588235     0.000000     0.000000    0.0  2104.000000
        8      1073.250000     0.000000     0.000000    0.0  1721.000000
        9       967.468750     0.000000  1399.000000    0.0  1724.600000
        11     1111.695652     0.000000  1399.000000    0.0  1733.000000
        12      961.850000     0.000000  1399.000000    0.0  2102.000000
B6      1      2456.428571     0.000000     0.000000    0.0   790.800000
        2      2475.600000     0.000000     0.000000    0.0   803.500000
        3      2430.666667     0.000000     0.000000    0.0  1298.200000
        4      2449.000000     0.000000     0.000000    0.0   782.333333
        5      2487.727273     0.000000     0.000000    0.0  1023.333333
        6      2501.250000     0.000000     0.000000    0.0  1004.333333
        7      2486.076923     0.000000     0.000000    0.0   941.909091
        8      2504.142857     0.000000     0.000000    0.0  1226.333333
...                    ...          ...          ...    ...          ...
UA      11     1724.073529     0.000000   751.882353    0.0  1060.460123
        12     1715.671875     0.000000   740.333333    0.0  1092.473333
US      1      1789.666667     0.000000  1074.615385    0.0   963.050000
        2      1804.375000     0.000000  1024.833333    0.0   867.100000
        3      1788.083333     0.000000  1060.714286    0.0   845.777778
        4      1760.500000     0.000000  1113.714286    0.0   914.444444
        5      1820.954545     0.000000  1014.200000    0.0   829.000000
        6      1363.000000     0.000000  1056.444444    0.0   937.947368
VX      1      1291.750000     0.000000     0.000000    0.0  1744.000000
        2      1277.764706  2532.500000     0.000000    0.0  1846.000000
        3      1530.538462     0.000000     0.000000    0.0     0.000000
        4      1514.743590   236.000000     0.000000    0.0  1778.000000
        5      1568.030303     0.000000     0.000000    0.0  1846.000000
        6      1572.242424     0.000000     0.000000    0.0  1805.200000
        7      1102.259259     0.000000     0.000000    0.0  1795.000000
        8      1192.000000     0.000000     0.000000    0.0  1778.000000
        9      1858.540541     0.000000     0.000000    0.0  1846.000000
        11     1346.621622     0.000000     0.000000    0.0  1846.000000
        12     1283.250000     0.000000     0.000000    0.0  1825.600000
WN      1       821.336735   512.000000   669.833333  349.0     0.000000
        2       741.121951   526.000000   549.636364    0.0     0.000000
        3       721.775510   337.000000   640.062500    0.0     0.000000
        4       750.638298   322.500000   658.590909    0.0     0.000000
        5       867.231481   236.000000   446.722222    0.0     0.000000
        6       855.044643     0.000000   693.750000    0.0     0.000000
        7       912.453704   327.777778   647.266667    0.0     0.000000
        8       835.404040   346.000000   508.703704    0.0     0.000000
        9       830.210000   317.666667   644.416667    0.0     0.000000
        11      748.404040   459.333333   573.642857    0.0     0.000000
        12      811.695238  1067.000000   634.736842    0.0     0.000000



ORG_AIR                             PHX                       SFO
CANCELLED                1            0            1            0            1
AIRLINE MONTH
AA      1         0.000000  1167.666667     0.000000  1860.166667     0.000000
        2       771.142857  1311.461538   868.000000  1337.916667  2586.000000
        3       802.000000  1171.363636     0.000000  1502.758621     0.000000
        4       943.600000  1266.214286     0.000000  1646.903226     0.000000
        5       999.500000  1240.444444     0.000000  1436.892857     0.000000
        6      1033.000000  1489.571429     0.000000  1671.517241     0.000000
        7      1330.333333  1163.835165  1494.000000  1771.000000   337.000000
        8      1168.000000  1198.901961  2979.000000  1735.020833     0.000000
        9         0.000000  1161.489510     0.000000  1770.540541     0.000000
        11      714.000000  1121.411765     0.000000  1597.325000     0.000000
        12      954.000000  1212.454545     0.000000  1765.564103     0.000000
AS      1         0.000000  1588.666667     0.000000   636.000000     0.000000
        2         0.000000  1107.000000     0.000000   621.500000     0.000000
        3         0.000000  1090.666667     0.000000   620.363636     0.000000
        4         0.000000  1271.428571     0.000000   629.333333     0.000000
        5         0.000000  1045.750000     0.000000   579.769231     0.000000
        6         0.000000  1107.000000     0.000000   621.666667     0.000000
        7         0.000000  1082.500000     0.000000   570.636364     0.000000
        8         0.000000  1082.500000     0.000000   558.909091     0.000000
        9         0.000000  1107.000000     0.000000   607.153846     0.000000
        11        0.000000  1058.000000     0.000000   613.090909     0.000000
        12        0.000000  1077.600000     0.000000   636.545455     0.000000
B6      1         0.000000  2202.000000     0.000000  1575.733333  2704.000000
        2         0.000000  2300.000000     0.000000  2198.300000     0.000000
        3         0.000000  2300.000000     0.000000  1645.642857     0.000000
        4         0.000000  2182.400000     0.000000  1835.285714     0.000000
        5         0.000000     0.000000     0.000000  2102.461538     0.000000
        6         0.000000     0.000000     0.000000  1771.000000     0.000000
        7         0.000000     0.000000     0.000000  1559.866667     0.000000
        8         0.000000     0.000000     0.000000  2255.846154     0.000000
...                    ...          ...          ...          ...          ...
UA      11      864.000000  1130.777778     0.000000  1438.823529   337.000000
        12      898.333333  1134.583333     0.000000  1686.180328  2446.000000
US      1         0.000000  1088.168067  2187.500000  1561.588235   651.000000
        2       638.500000  1231.360360  1495.666667  1908.727273     0.000000
        3       678.000000  1180.205882  2917.000000  2099.181818  2521.000000
        4         0.000000  1163.559748  2917.000000  1890.285714     0.000000
        5       678.000000  1093.541401     0.000000  1354.000000     0.000000
        6         0.000000  1208.267857     0.000000  2059.333333     0.000000
VX      1         0.000000     0.000000     0.000000   978.976190  2704.000000
        2         0.000000     0.000000     0.000000  1099.555556   679.000000
        3         0.000000     0.000000     0.000000  1280.155556     0.000000
        4         0.000000     0.000000     0.000000  1123.642857     0.000000
        5         0.000000     0.000000     0.000000  1358.552632     0.000000
        6         0.000000     0.000000     0.000000  1079.372549     0.000000
        7         0.000000     0.000000     0.000000  1475.634146   337.000000
        8         0.000000     0.000000     0.000000  1176.369565     0.000000
        9         0.000000     0.000000     0.000000  1208.116279     0.000000
        11        0.000000     0.000000     0.000000  1209.150000     0.000000
        12        0.000000     0.000000     0.000000  1218.905660     0.000000
WN      1         0.000000   812.300699     0.000000   714.800000   337.000000
        2         0.000000   788.889655   886.000000   715.026316   388.000000
        3         0.000000   819.783951   651.000000   600.750000     0.000000
        4         0.000000   794.147239   255.000000   685.222222   392.000000
        5         0.000000   786.056250     0.000000   703.244898   392.000000
        6         0.000000   829.653631     0.000000   721.125000   361.166667
        7         0.000000   799.160256   369.000000   636.210526     0.000000
        8         0.000000   891.569767     0.000000   644.857143   392.000000
        9         0.000000   872.840000     0.000000   731.578947   354.500000
        11        0.000000   823.258741   872.000000   580.875000   392.000000
        12        0.000000   778.420690     0.000000   782.256410     0.000000

[149 rows x 80 columns]

In [10]:
flights.groupby(['AIRLINE', 'MONTH', 'ORG_AIR', 'CANCELLED'])['DEP_DELAY', 'DIST'].agg(['mean', 'sum']).unstack(['ORG_AIR', 'CANCELLED'], fill_value=0).swaplevel(0, 1, axis='columns')

                    mean                                                 \
               DEP_DELAY
ORG_AIR              ATL            DEN             DFW             IAH
CANCELLED              0   1          0    1          0    1          0
AIRLINE MONTH
AA      1      -3.250000 NaN   7.062500  NaN  11.977591 -3.0   9.750000
        2      -3.000000 NaN   5.461538  NaN   8.756579  NaN   1.000000
        3      -0.166667 NaN   7.666667  NaN  15.383784  NaN  10.900000
        4       0.071429 NaN  20.266667  NaN  10.501493  NaN   6.933333
        5       5.777778 NaN  23.466667  NaN  16.798780  NaN   3.055556
        6       6.400000 NaN   0.916667  NaN  16.727041  NaN  77.571429
        7      15.131579 NaN   3.478261  NaN  11.014815  NaN  37.592593
        8       3.473684 NaN  21.000000  NaN  10.688385  NaN   4.483871
        9      14.730769 NaN   3.135135  NaN   6.166240  NaN   2.142857
        11      8.600000 NaN  16.833333  NaN  10.222222  NaN   5.200000
        12     12.774194 NaN   5.260870  NaN   6.938776  NaN  13.315789
AS      1            NaN NaN  -3.400000  NaN  -1.200000  NaN   0.000000
        2       0.500000 NaN  -5.000000  NaN   3.200000  NaN        NaN
        3      -2.000000 NaN -12.000000  NaN   3.500000  NaN        NaN
        4       3.500000 NaN  -3.750000  NaN   2.000000  NaN   8.000000
        5      17.000000 NaN   1.000000  NaN  22.500000  NaN -15.000000
        6            NaN NaN   4.142857  NaN   0.500000  NaN -13.000000
        7            NaN NaN   1.600000  NaN  -7.750000  NaN  -9.000000
        8      41.000000 NaN  -8.000000  NaN   2.600000  NaN        NaN
        9            NaN NaN  -3.500000  NaN  -8.333333  NaN  -6.000000
        11     -3.000000 NaN  -6.000000  NaN  -7.000000  NaN        NaN
        12     43.500000 NaN  -8.333333  NaN  11.400000  NaN -13.000000
B6      1            NaN NaN   4.500000  NaN  -0.500000  NaN        NaN
        2            NaN NaN  23.666667  NaN  31.500000  NaN        NaN
        3            NaN NaN  31.000000  NaN        NaN  NaN        NaN
        4            NaN NaN  -3.750000  NaN  -7.000000  NaN        NaN
        5            NaN NaN   7.500000  NaN  -1.600000  NaN        NaN
        6            NaN NaN  22.333333  NaN  10.500000  NaN        NaN
        7            NaN NaN        NaN  NaN        NaN  NaN        NaN
        8            NaN NaN  12.666667  NaN  63.000000  NaN        NaN
...                  ...  ..        ...  ...        ...  ...        ...
UA      11     23.250000 NaN   7.927419  NaN  -5.666667  NaN  13.379310
        12     43.750000 NaN  19.053030  NaN  15.111111  NaN  19.896552
US      1      -4.222222 NaN   0.333333  NaN   1.958333  NaN  -5.200000
        2      -0.500000 NaN   6.555556  NaN   1.538462  NaN   1.466667
        3      -2.666667 NaN   2.416667  NaN   7.000000  NaN  -4.461538
        4      -3.250000 NaN  -5.357143  NaN   8.307692  NaN   8.333333
        5       8.533333 NaN   7.909091  NaN   1.842105  NaN  -3.000000
        6      11.363636 NaN  -2.700000  NaN  15.000000  NaN  -0.904762
VX      1            NaN NaN        NaN  NaN        NaN  NaN        NaN
        2            NaN NaN        NaN  NaN        NaN  NaN        NaN
        3            NaN NaN        NaN  NaN        NaN  NaN        NaN
        4            NaN NaN        NaN  NaN        NaN  NaN        NaN
        5            NaN NaN        NaN  NaN        NaN  NaN        NaN
        6            NaN NaN        NaN  NaN        NaN  NaN        NaN
        7            NaN NaN        NaN  NaN        NaN  NaN        NaN
        8            NaN NaN        NaN  NaN        NaN  NaN        NaN
        9            NaN NaN        NaN  NaN        NaN  NaN        NaN
        11           NaN NaN        NaN  NaN        NaN  NaN        NaN
        12           NaN NaN        NaN  NaN        NaN  NaN        NaN
WN      1       8.764706 NaN  14.273438  NaN        NaN  NaN        NaN
        2       7.285714 NaN  13.504950  NaN        NaN  NaN        NaN
        3      10.733945 NaN  13.075342  NaN        NaN  NaN        NaN
        4      11.376147 NaN  14.703125  NaN        NaN  NaN        NaN
        5      15.224806 NaN  13.509677 -2.0        NaN  NaN        NaN
        6      22.819820 NaN  16.398649  NaN        NaN  NaN        NaN
        7      21.700000 NaN  13.143836  NaN        NaN  NaN        NaN
        8      16.207547 NaN   7.375000  NaN        NaN  NaN        NaN
        9       8.680672 NaN   4.378882  NaN        NaN  NaN        NaN
        11      5.932203 NaN   8.215569  NaN        NaN  NaN        NaN
        12     15.691589 NaN  12.166667  NaN        NaN  NaN        NaN

                                      ...         sum                          \
                                      ...        DIST
ORG_AIR                     LAS       ...         LAX              MSP
CANCELLED          1          0   1   ...           0       1        0      1
AIRLINE MONTH                         ...
AA      1        NaN  32.375000 NaN   ...    135921.0  2475.0   7281.0    NaN
        2        NaN  -3.055556 NaN   ...    113483.0  5454.0   5040.0    NaN
        3        NaN  12.074074 NaN   ...    131836.0  1744.0  14471.0    NaN
        4        NaN  27.241379 NaN   ...    170285.0     NaN   4541.0    NaN
        5        NaN   2.818182 NaN   ...    167484.0     NaN   6298.0    NaN
        6        NaN  38.391304 NaN   ...    158554.0     NaN   3539.0    NaN
        7        NaN   7.500000 NaN   ...    170524.0     NaN  18878.0  980.0
        8        NaN   5.650000 NaN   ...    184865.0  4300.0  14867.0    NaN
        9        NaN  -2.055556 NaN   ...    136870.0  1235.0  16606.0    NaN
        11       NaN   6.644444 NaN   ...    148134.0  1744.0  18615.0  930.0
        12       NaN  -0.340909 NaN   ...    186587.0  4230.0  15906.0  334.0
AS      1        NaN   5.833333 NaN   ...     16731.0     NaN   2798.0    NaN
        2        NaN  72.666667 NaN   ...     19426.0     NaN      NaN    NaN
        3        NaN  -5.300000 NaN   ...     22646.0     NaN   1399.0    NaN
        4        NaN  -4.769231 NaN   ...     25653.0     NaN      NaN    NaN
        5        NaN  14.571429 NaN   ...     24564.0     NaN   5596.0    NaN
        6        NaN  -4.909091 NaN   ...     31560.0     NaN   2798.0    NaN
        7        NaN  -9.166667 NaN   ...     33170.0     NaN      NaN    NaN
        8        NaN  -6.733333 NaN   ...     17172.0     NaN      NaN    NaN
        9        NaN  -3.714286 NaN   ...     30959.0     NaN   1399.0    NaN
        11       NaN  -7.166667 NaN   ...     25569.0     NaN   5596.0    NaN
        12       NaN  -5.538462 NaN   ...     19237.0     NaN   1399.0    NaN
B6      1        NaN  19.666667 NaN   ...     17195.0     NaN      NaN    NaN
        2        NaN   6.500000 NaN   ...     24756.0     NaN      NaN    NaN
        3        NaN  19.428571 NaN   ...     14584.0     NaN      NaN    NaN
        4        NaN  -2.428571 NaN   ...     24490.0     NaN      NaN    NaN
        5        NaN   1.444444 NaN   ...     27365.0     NaN      NaN    NaN
        6        NaN  12.125000 NaN   ...     40020.0     NaN      NaN    NaN
        7        NaN  17.307692 NaN   ...     32319.0     NaN      NaN    NaN
        8        NaN  16.142857 NaN   ...     35058.0     NaN      NaN    NaN
...              ...        ...  ..   ...         ...     ...      ...    ...
UA      11       NaN  14.562500 NaN   ...    117237.0     NaN  12782.0    NaN
        12     227.0  26.625000 NaN   ...    109803.0     NaN   4442.0    NaN
US      1        NaN  -5.357143 NaN   ...     32214.0     NaN  13970.0    NaN
        2        NaN  -5.090909 NaN   ...     28870.0     NaN  12298.0    NaN
        3        NaN  -1.933333 NaN   ...     21457.0     NaN  14850.0    NaN
        4        NaN  -1.062500 NaN   ...     42252.0     NaN  15592.0    NaN
        5        NaN  -3.642857 NaN   ...     40061.0     NaN  10142.0    NaN
        6        NaN  -0.750000 NaN   ...     27260.0     NaN   9508.0    NaN
VX      1        NaN   2.600000 NaN   ...     41336.0     NaN      NaN    NaN
        2        NaN  13.375000 NaN   ...     43444.0  5065.0      NaN    NaN
        3        NaN   0.500000 NaN   ...     39794.0     NaN      NaN    NaN
        4        NaN   8.454545 NaN   ...     59075.0   236.0      NaN    NaN
        5        NaN   6.153846 NaN   ...     51745.0     NaN      NaN    NaN
        6        NaN   4.272727 NaN   ...     51884.0     NaN      NaN    NaN
        7        NaN  23.900000 NaN   ...     29761.0     NaN      NaN    NaN
        8        NaN   2.200000 NaN   ...     38144.0     NaN      NaN    NaN
        9        NaN  -1.750000 NaN   ...     68766.0     NaN      NaN    NaN
        11       NaN   3.800000 NaN   ...     49825.0     NaN      NaN    NaN
        12       NaN   3.000000 NaN   ...     41064.0     NaN      NaN    NaN
WN      1        NaN   9.692308 NaN   ...     80491.0  1536.0  16076.0  349.0
        2        NaN   6.696203 NaN   ...     60772.0  1052.0  12092.0    NaN
        3        NaN  11.515152 NaN   ...     70734.0  1011.0  10241.0    NaN
        4        NaN  11.323864 NaN   ...     70560.0   645.0  14489.0    NaN
        5        NaN  11.766839 NaN   ...     93661.0   236.0   8041.0    NaN
        6        NaN  17.350000 NaN   ...     95765.0     NaN  13875.0    NaN
        7        NaN  22.439024 NaN   ...     98545.0  2950.0  19418.0    NaN
        8        NaN  16.158974 NaN   ...     82705.0  1384.0  13735.0    NaN
        9        NaN   7.179487 NaN   ...     83021.0   953.0  15466.0    NaN
        11       NaN   7.522989 NaN   ...     74092.0  1378.0   8031.0    NaN
        12       NaN  11.994845 NaN   ...     85228.0  2134.0  12060.0    NaN



ORG_AIR             ORD               PHX               SFO
CANCELLED             0       1         0       1         0       1
AIRLINE MONTH
AA      1      129334.0     NaN   21018.0     NaN   33483.0     NaN
        2      120572.0  5398.0   17049.0   868.0   32110.0  2586.0
        3      127072.0   802.0   25770.0     NaN   43580.0     NaN
        4      152154.0  4718.0   17727.0     NaN   51054.0     NaN
        5      110864.0  1999.0   11164.0     NaN   40233.0     NaN
        6      173702.0  4132.0   20854.0     NaN   48474.0     NaN
        7      175049.0  3991.0  211818.0  2988.0   70840.0   337.0
        8      160407.0  3504.0  183432.0  2979.0   83281.0     NaN
        9      139792.0     NaN  166093.0     NaN   65510.0     NaN
        11     135282.0  4284.0  171576.0     NaN   63893.0     NaN
        12     139413.0  3816.0  186718.0     NaN   68857.0     NaN
AS      1        6288.0     NaN    4766.0     NaN    7632.0     NaN
        2        6884.0     NaN    5535.0     NaN    8701.0     NaN
        3        6902.0     NaN    6544.0     NaN    6824.0     NaN
        4        8027.0     NaN    8900.0     NaN    7552.0     NaN
        5       14911.0     NaN    8366.0     NaN    7537.0     NaN
        6        8623.0     NaN    8856.0     NaN   11190.0     NaN
        7       18936.0     NaN    4330.0     NaN    6277.0     NaN
        8        6884.0     NaN    4330.0     NaN    6148.0     NaN
        9        8623.0     NaN    5535.0     NaN    7893.0     NaN
        11       5199.0     NaN    4232.0     NaN    6744.0     NaN
        12       6306.0     NaN   10776.0     NaN    7002.0     NaN
B6      1        3954.0     NaN    6606.0     NaN   23636.0  2704.0
        2        3214.0     NaN    6900.0     NaN   21983.0     NaN
        3        6491.0     NaN    2300.0     NaN   23039.0     NaN
        4        2347.0     NaN   10912.0     NaN   25694.0     NaN
        5       15350.0     NaN       NaN     NaN   27332.0     NaN
        6        6026.0     NaN       NaN     NaN   28336.0     NaN
        7       10361.0     NaN       NaN     NaN   23398.0     NaN
        8        7358.0     NaN       NaN     NaN   29326.0     NaN
...                 ...     ...       ...     ...       ...     ...
UA      11     172855.0   864.0   20354.0     NaN  171220.0   337.0
        12     163871.0  2695.0   13615.0     NaN  205714.0  2446.0
US      1       19261.0     NaN  129492.0  4375.0   26547.0   651.0
        2        8671.0  1277.0  136681.0  4487.0   20996.0     NaN
        3       15224.0  2034.0  160508.0  2917.0   23091.0  5042.0
        4       16460.0     NaN  185006.0  2917.0   13232.0     NaN
        5        9948.0   678.0  171686.0     NaN   13540.0     NaN
        6       17821.0     NaN  202989.0     NaN   24712.0     NaN
VX      1        1744.0     NaN       NaN     NaN   41117.0  2704.0
        2        1846.0     NaN       NaN     NaN   39584.0   679.0
        3           NaN     NaN       NaN     NaN   57607.0     NaN
        4        5334.0     NaN       NaN     NaN   47193.0     NaN
        5        7384.0     NaN       NaN     NaN   51625.0     NaN
        6        9026.0     NaN       NaN     NaN   55048.0     NaN
        7       14360.0     NaN       NaN     NaN   60501.0   337.0
        8        5334.0     NaN       NaN     NaN   54113.0     NaN
        9        1846.0     NaN       NaN     NaN   51949.0     NaN
        11      18460.0     NaN       NaN     NaN   48366.0     NaN
        12       9128.0     NaN       NaN     NaN   64602.0     NaN
WN      1           NaN     NaN  116159.0     NaN   21444.0  1348.0
        2           NaN     NaN  114389.0  1772.0   27171.0  1940.0
        3           NaN     NaN  132805.0   651.0   21627.0     NaN
        4           NaN     NaN  129446.0   255.0   24668.0   784.0
        5           NaN     NaN  125769.0     NaN   34459.0   784.0
        6           NaN     NaN  148508.0     NaN   34614.0  2167.0
        7           NaN     NaN  124669.0   369.0   24176.0     NaN
        8           NaN     NaN  153350.0     NaN   18056.0   784.0
        9           NaN     NaN  130926.0     NaN   27800.0   709.0
        11          NaN     NaN  117726.0   872.0   23235.0   784.0
        12          NaN     NaN  112871.0     NaN   30508.0     NaN

[149 rows x 80 columns]